# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a93d8212d23baf599ad3c98683fe0a6bf3946d9f68a3875647b242425b6cb4e87d06bd68da8f61b6c2f69a8338f08c070f8178627ad1237e3c5d759740c90b9

test:
  secret_key_base: 6a9982ec7e7e21d15878d73f38bf90d1023662d1b217c53c19dfdc66dcda40126b7eec83ef4e1f2168cb81586863ada4c57c3c77cc824e4d5b5778aa7f74fc24

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
